sudo: required
services:
  - docker

before_install:
  - docker build -t testme -f Dockerfile.dev .

script:
  - docker run -e CI=true testme npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-reactapp"
  env: "DockerReactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-194842585266"
  bucket_path: "docker-reactapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
